### ISSUE TITLE
Users should be able to define AND searches, not just OR searches. 

### ISSUE THREAD

**Issue by jdagdelen** [materialsintelligence/matscholar-web#109]
For example, if I wanted to find synthesis methods for gold nanoparticles. 

Right now, the search "material: Au, descriptor: nanoparticles" gives every paper that mentions Au or nanoparticles, but in this case I want ever paper that mentions both Au and nanoparticles.

**Comment by ardunn** [comment]
wait, this explains so much
I thought it was doing AND searches already

**Comment by AmalieT** [comment]
I think this one deserves thought and collaboration with front end. How
should this look to users to be as simple and transparent as possible? Then
what does the resultant query look like optimally? Maybe we should discuss
this at the meeting tomorrow.

**Comment by ardunn** [comment]
## The simplest thing
I think the absolute simplest thing to do would be to literally have a dropdown menu where you select "AND" or "OR". Select "AND" and all the terms will be linked in AND fashion; select "OR" and the terms will be searched in "OR" fashion. The default would be "AND", since up until @jdagdelen put this comment, that's what I thought it was (and I think new users would come to a similar assumption in its current state). 

Yes, this is a limiting approach; but I would guess most queries will either be ALL AND or ALL OR anyway.

Example: I want to know about "material: Au" AND "descriptor: nanoparticles" AND "characterization: SEM". I.e., specifically the characterization of gold nanoparticles with SEM. 

Example 2: I want to know everything about "application: spintronics" OR "application: tunnel magnetoresistance" OR "property: spin orbit torque". i.e., just tell me (generally) everything about the physics of spintronics and an application.

Also, this way is rock-dumb simple (from a frontend perspective) and could be done within a day provided the rester is set up to handle AND searches. 

## More complicated
Of course there are scenarios where you might want both AND and OR. For example, "phase: superlattice" AND "material: PbSe" OR "material: SnSe". Doing this in a user friendly way (i.e., without them having to type in some query language that we have to explain to them) seems not so easy, but maybe something we can figure out in the meeting. If this more complicated way is what we do, we should probably just write it when we do a universal search bar (v3) because it kind of breaks the design paradigm of the current website (v2).

**Comment by jdagdelen** [comment]
I think default behavior should always be AND. If users want an OR they can do separate searches.

On Mon, Sep 30, 2019 at 7:39 PM, Alex Dunn <notifications@github.com> wrote:
THE SIMPLEST THING
I think the absolute simplest thing to do would be to literally have a dropdown menu where you select "AND" or "OR". Select "AND" and all the terms will be linked in AND fashion; select "OR" and the terms will be searched in "OR" fashion. The default would be "AND", since up until @jdagdelen [https://github.com/jdagdelen] put this comment, that's what I thought it was (and I think new users would come to a similar assumption in its current state).

Yes, this is a limiting approach; but I would guess most queries will either be ALL AND or ALL OR anyway.

Example: I want to know about "material: Au" AND "descriptor: nanoparticles" AND "characterization: SEM". I.e., specifically the characterization of gold nanoparticles with SEM.

Example 2: I want to know everything about "application: spintronics" OR "application: tunnel magnetoresistance" OR "property: spin orbit torque". i.e., just tell me (generally) everything about the physics of spintronics and an application.

Also, this way is rock-dumb simple (from a frontend perspective) and could be done within a day provided the rester is set up to handle AND searches.

MORE COMPLICATED
Of course there are scenarios where you might want both AND and OR. For example, "phase: superlattice" AND "material: PbSe" OR "material: SnSe". Doing this in a user friendly way (i.e., without them having to type in some query language that we have to explain to them) seems not so easy, but maybe something we can figure out in the meeting.

**Comment by ardunn** [comment]
> I think default behavior should always be AND. If users want an OR they can do separate searches

Fine by me.

**Comment by computron** [comment]
I agree default should always be AND. No support for OR in the short term, we can do something more complicated later

**Comment by AmalieT** [comment]
AND was the default behaviour all along - what was happening here was in fact a somewhat subtle bug whereby in certain circumstances materials formula could be put in lower case (and subsequently ignored in searches.) That's now been resolved.

**Comment by ardunn** [comment]
@AmalieT excellent work. Saved us a lot of work lol
