### ISSUE TITLE
[multiple parsing issues] the need for a comma in the search field is unintuitive / difficult to remember

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#146]
e.g. this works

"material: Bi2Te3, property: thermoelectrics"

this doesn't
"material: Bi2Te3 property: thermoelectrics"

**Comment by ardunn** [comment]
similarly, multiple searches for one entity type does not work:

`material: Au, AuCl4H` returns the same thing as `material: Au`

**Comment by ardunn** [comment]
Also, the following search:

```
traw: Zintl
```

is somehow parsed to `{raw: t Zintl}` instead of just throwing an error, like it should.??

**Comment by ardunn** [comment]
We should actually discuss what the intended behavior should be, since people should (1) be able to enter multiple terms for a given entity and (2) not have to use commas to separate, but doing both of these at the same time is hard (bc some terms can have spaces):... maybe something to talk about at next meeting

**Comment by computron** [comment]
I think commas to separate within a given entity is fine, but not when switching entities. e.g., like the following

"material: PbTe, Bi2Te3 application: thermoelectric"

The comma separates the materials, but you don't need yet another comma after Bi2Te3

Also note that I don't like ``traw``. No one will remember your convention that this means "text_raw" or whatever. Remember that this web site is for experimentalists and casual users

**Comment by ardunn** [comment]
>I think commas to separate within a given entity is fine, but not when switching entities. e.g., like the following

Sounds good. This is doable then.

> Also note that I don't like traw. No one will remember your convention that this means "text_raw" or whatever. Remember that this web site is for experimentalists and casual users

@computron yes, the "traw" is not intended! I accidentally typed `traw: Zintl` and was surprised when it actually returned something **instead of throwing a warning like it was intended to**. The keyword is `raw` and only `raw`. `traw` _should_ throw an error but  _didnt_.

**Comment by ardunn** [comment]
All these parsing issues are resolved (at least on the frontend) by: 72bcc1f48ef7434c9289f9c634304aa0bb0549f0
