### ISSUE TITLE
Thoughts from a new user: general interface is confusing

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#91]
This is a list of very opinionated things I did not like about the website (perhaps to be added as individual issues if we decide to stick with the current format) based on the presentation @AmalieT gave at the hackathon and from playing around on it as a new user. I understand if people disagree but I thought I'd put them here anyway

Pinging @mkhorton as he might be interested/have thoughts.

# Impressions
## Main search box

On the *front page*, there are 10 search boxes with no real instructions on how to use them. It took me a minute to figure out how to use it. 

The first one is a full text search. As @AmalieT tells me, this is not the text box we want people using. If it is not the full text search we want people using, why is it the first and largest thing on the page? 

![image](https://user-images.githubusercontent.com/19936203/64444831-e609a700-d089-11e9-97a7-5b8b58faa90f.png)

When I search for most terms, the website times out or otherwise glitches. For example, when I search for barium titanate in the main search box, I get timed out. If I was a scientist looking at this page and wasn't associated with the project, I'd probably just leave without playing around with much. I get that searching for formula isn't the thing you're "supposed" to search for in the full text box, but it just says "Enter search terms" without anything else. How am I supposed to know what to enter here?

## Filter boxes

The other 9 search boxes are technically filters but it's unclear to an outside user what to do with them. There is no text or explanation that these boxes are for searching entities and are entirely different from a full text search. There is also nothing that lets me know that you can use these boxes independently from the full text search. 

Why can't I just hit enter to search *only* with the filter boxes? At present it seems I have to hit search directly.

 **Minor**: Autocomplete brings up related materials in a janky order
![image](https://user-images.githubusercontent.com/19936203/64446383-81e8e200-d08d-11e9-88c7-08b823cad47d.png)

I type in PbTe, why is the first thing that comes up Mn2Sn18(PbTe5)5?

## Statistics/Papers/Materials radio buttons

If we want to "wow" new users, it might be nice to just return Statistics **and** Papers **and** Materials with a **single** query. I.e., I search for PbTe, it gives me everything it knows about PbTe. I'd rather search for something and it bring up a lot of info for me to search through than have to click through 3 options. At the very least, we should re-word each option so it is clearer what exactly I'm getting back. E.g., `Statistics` --> `Words associated with Query` (or some more elegantly/accurately worded version).

When switching between radio buttons, it currently does not switch my query after I have already searched, even though the "searching" animation appears. It appears to be "searching" but just displays the old output; to get what I am actually searching for requires me to hit the "search" button again, which is unintuitive. 

![image](https://user-images.githubusercontent.com/19936203/64446010-9e384f00-d08c-11e9-9099-bb03d8713429.png)
![image](https://user-images.githubusercontent.com/19936203/64446030-a7c1b700-d08c-11e9-8f3e-fb81ea35c950.png)

If I refresh the page and search again, and go through entering something into the filter boxes (without entering a full search term), ~50% of the time I get no results back, even for terms that were autosuggested. Here I tried PbTe and thermoelectric, which should work:

![image](https://user-images.githubusercontent.com/19936203/64459830-c1272b00-d0ad-11e9-9544-49173bb2de97.png)

## Results area

When opening DOIs under the 'Papers' option, the text goes off the page...
![image](https://user-images.githubusercontent.com/19936203/64446931-fcfec800-d08e-11e9-96ec-0e0f537aae1f.png)

Statistics page looks strange when there are different numbers of results for each entity type. The boxes are misaligned and there's big white spaces everywhere.
![image](https://user-images.githubusercontent.com/19936203/64447502-5e736680-d090-11e9-9321-dcc5c4dad9aa.png)

## "analyze" page

"analyze" by itself is not clear. Why not "Analyze an abstract"?

Abstract text goes off the page.
![image](https://user-images.githubusercontent.com/19936203/64446894-d8a2eb80-d08e-11e9-9502-a7e745f812bc.png)

## Random/Very minor

Bright yellow on white doesn't look good.
![image](https://user-images.githubusercontent.com/19936203/64447601-a2ff0200-d090-11e9-8f34-ad7d01e9e0b8.png)

The text in general is small.

There aren't any examples of how to use the multiple search boxes.

As we discussed in meeting, being able to filter by year and author would be cool.

# Suggestion

#### As we talked in the meeting, given the state of the front end code, a full-on reworking of the front-end might be the easiest way to go?

If that is the case, I attached some **very very rough** mockups of my own personal "dream" version of matscholar-web. Maybe too ambitious or opinionated (and again, very rough), but I'll put it here nonetheless. 

![landing page](https://user-images.githubusercontent.com/19936203/64457559-c5504a00-d0a7-11e9-89df-b744d5992569.png)

This is the landing page. The main box is a "Quick search" box where users can enter materials-related search terms. User types in comma separated terms. Help is available on how to use the search.

![entered_terms](https://user-images.githubusercontent.com/19936203/64457722-427bbf00-d0a8-11e9-8def-64b23f563d64.png)
 
The user enters some terms. Hit enter, and the request is sent. Backend tries to interpret each term as an entity. This would be the biggest change and challenge of this setup, but I think would make things way easier and more intuitive for users. People who have worked on the backend (@AmalieT, @jdagdelen, @LeighWeston86) would probably be able to tell whether something like this is feasible. If it's not, something like #64 ?

![results](https://user-images.githubusercontent.com/19936203/64458370-05b0c780-d0aa-11e9-99a4-a187a640c488.png)

Results are shown. Papers, materials, and statistics are shown on the same page. There is also a table for how the search was interpreted (i.e., `LiCoO2` is a material, `battery` and `cathode` are applications). This is how a query to the existing API is formed. 

A drop down menu can limit which results you want to see. Links to lists of clickable dois are available for when, for example, there are more than 10 DOIs and they won't fit all on one page. 

If the quick search didn't work as expected or the results you found aren't good enough, you can go to the advanced search page, which is similar to the existing search page. You can enter the entities individually. It should function identically to the current search page, just maybe a bit clearer as to the order of operations needed to actually *run* a search.  You can also filter according to author and year. The quick search bar is available as it was on the landing page. When you run the advanced search, a query to the existing API is formed in the same way it is now. When the search returns, you get the same kind of results page as for the quick search. 

![advanced search](https://user-images.githubusercontent.com/19936203/64457968-f715e080-d0a8-11e9-981b-60f286077470.png)

The analyze abstract page is functionally identical to the existing analyze page. You can still quick search from this page.

![abstract_extraction](https://user-images.githubusercontent.com/19936203/64458162-72779200-d0a9-11e9-804f-4df2d0d634eb.png)

**Comment by jdagdelen** [comment]
I think these suggestions are very good and many of the rough spots you’ve pointed out are things that have come up in our previous discussions. Your proposed UI changes are particularly very excited and I think we should go in that direction. You have my full support to implement the UI as you have suggested.
On Sat, Sep 7, 2019 at 12:00 AM, Alex Dunn <notifications@github.com> wrote:
This is a list of very opinionated things I did not like about the website (perhaps to be added as individual issues if we decide to stick with the current format) based on the presentation @AmalieT [https://github.com/AmalieT] gave at the hackathon and from playing around on it as a new user. I understand if people disagree but I thought I'd put them here anyway

Pinging @mkhorton [https://github.com/mkhorton] as he might be interested/have thoughts.

IMPRESSIONS
MAIN SEARCH BOX
On the front page , there are 10 search boxes with no real instructions on how to use them. It took me a minute to figure out how to use it.

The first one is a full text search. As @AmalieT [https://github.com/AmalieT] tells me, this is not the text box we want people using. If it is not the full text search we want people using, why is it the first and largest thing on the page?

[https://user-images.githubusercontent.com/19936203/64444831-e609a700-d089-11e9-97a7-5b8b58faa90f.png]

When I search for most terms, the website times out or otherwise glitches. For example, when I search for barium titanate in the main search box, I get timed out. If I was a scientist looking at this page and wasn't associated with the project, I'd probably just leave without playing around with much. I get that searching for formula isn't the thing you're "supposed" to search for in the full text box, but it just says "Enter search terms" without anything else. How am I supposed to know what to enter here?

FILTER BOXES
The other 9 search boxes are technically filters but it's unclear to an outside user what to do with them. There is no text or explanation that these boxes are for searching entities and are entirely different from a full text search. There is also nothing that lets me know that you can use these boxes independently from the full text search.

Why can't I just hit enter to search only with the filter boxes? At present it seems I have to hit search directly.

Minor : Autocomplete brings up related materials in a janky order
[https://user-images.githubusercontent.com/19936203/64446383-81e8e200-d08d-11e9-88c7-08b823cad47d.png]

I type in PbTe, why is the first thing that comes up Mn2Sn18(PbTe5)5?

STATISTICS/PAPERS/MATERIALS RADIO BUTTONS
If we want to "wow" new users, it might be nice to just return Statistics and Papers and Materials with a single query. I.e., I search for PbTe, it gives me everything it knows about PbTe. I'd rather search for something and it bring up a lot of info for me to search through than have to click through 3 options. At the very least, we should re-word each option so it is clearer what exactly I'm getting back. E.g., Statistics --> Words associated with Query (or some more elegantly/accurately worded version).

When switching between radio buttons, it currently does not switch my query after I have already searched, even though the "searching" animation appears. It appears to be "searching" but just displays the old output; to get what I am actually searching for requires me to hit the "search" button again, which is unintuitive.

[https://user-images.githubusercontent.com/19936203/64446010-9e384f00-d08c-11e9-9099-bb03d8713429.png]
[https://user-images.githubusercontent.com/19936203/64446030-a7c1b700-d08c-11e9-8f3e-fb81ea35c950.png]

If I refresh the page and search again, and go through entering something into the filter boxes (without entering a full search term), ~50% of the time I get no results back, even for terms that were autosuggested. Here I tried PbTe and thermoelectric, which should work:

[https://user-images.githubusercontent.com/19936203/64459830-c1272b00-d0ad-11e9-9544-49173bb2de97.png]

RESULTS AREA
When opening DOIs under the 'Papers' option, the text goes off the page...
[https://user-images.githubusercontent.com/19936203/64446931-fcfec800-d08e-11e9-96ec-0e0f537aae1f.png]

Statistics page looks strange when there are different numbers of results for each entity type. The boxes are misaligned and there's big white spaces everywhere.
[https://user-images.githubusercontent.com/19936203/64447502-5e736680-d090-11e9-9321-dcc5c4dad9aa.png]

"ANALYZE" PAGE
"analyze" by itself is not clear. Why not "Analyze an abstract"?

Abstract text goes off the page.
[https://user-images.githubusercontent.com/19936203/64446894-d8a2eb80-d08e-11e9-9502-a7e745f812bc.png]

RANDOM/VERY MINOR
Bright yellow on white doesn't look good.
[https://user-images.githubusercontent.com/19936203/64447601-a2ff0200-d090-11e9-8f34-ad7d01e9e0b8.png]

The text in general is small.

There aren't any examples of how to use the multiple search boxes.

As we discussed in meeting, being able to filter by year and author would be cool.

SUGGESTION
AS WE TALKED IN THE MEETING, GIVEN THE STATE OF THE FRONT END CODE, A FULL-ON REWORKING OF THE FRONT-END MIGHT BE THE EASIEST WAY TO GO?
If that is the case, I attached some very very rough mockups of my own personal "dream" version of matscholar-web. Maybe too ambitious or opinionated (and again, very rough), but I'll put it here nonetheless.

[https://user-images.githubusercontent.com/19936203/64457559-c5504a00-d0a7-11e9-89df-b744d5992569.png]

This is the landing page. The main box is a "Quick search" box where users can enter materials-related search terms. User types in comma separated terms. Help is available on how to use the search.

[https://user-images.githubusercontent.com/19936203/64457722-427bbf00-d0a8-11e9-8def-64b23f563d64.png]

The user enters some terms. Hit enter, and the request is sent. Backend tries to interpret each term as an entity. This would be the biggest change and challenge of this setup, but I think would make things way easier and more intuitive for users. People who have worked on the backend ( @AmalieT [https://github.com/AmalieT] , @jdagdelen [https://github.com/jdagdelen] , @LeighWeston86 [https://github.com/LeighWeston86] ) would probably be able to tell whether something like this is feasible. If it's not, something like #64 [https://github.com/materialsintelligence/matscholar-web/issues/64] ?

[https://user-images.githubusercontent.com/19936203/64458370-05b0c780-d0aa-11e9-99a4-a187a640c488.png]

Results are shown. Papers, materials, and statistics are shown on the same page. There is also a table for how the search was interpreted (i.e., LiCoO2 is a material, battery and cathode are applications). This is how a query to the existing API is formed.

A drop down menu can limit which results you want to see. Links to lists of clickable dois are available for when, for example, there are more than 10 DOIs and they won't fit all on one page.

If the quick search didn't work as expected or the results you found aren't good enough, you can go to the advanced search page, which is similar to the existing search page. You can enter the entities individually. It should function identically to the current search page, just maybe a bit clearer as to the order of operations needed to actually run a search. You can also filter according to author and year. The quick search bar is available as it was on the landing page. When you run the advanced search, a query to the existing API is formed in the same way it is now. When the search returns, you get the same kind of results page as for the quick search.

[https://user-images.githubusercontent.com/19936203/64457968-f715e080-d0a8-11e9-981b-60f286077470.png]

The analyze abstract page is functionally identical to the existing analyze page. You can still quick search from this page.

[https://user-images.githubusercontent.com/19936203/64458162-72779200-d0a9-11e9-804f-4df2d0d634eb.png]

**Comment by mkhorton** [comment]
I think this sounds very sensible, also in full support, +1 for simplicity and clarity first.

I have a few minor comments on the mock-up but will save them for now until there’s a working prototype.

**Comment by AmalieT** [comment]
100% support the changes you've suggested. And from a backend perspective,
everything you want to do is possible (although not necessarily currently
implemented).

**Comment by computron** [comment]
Hi Alex,

Thanks for taking the time to write up all these suggestions. Many of them are eerily similar to things we discussed in the past, but having them mocked up like this really helps in revisiting them.

Here are some of my comments on the proposed ideas:

1. The "Analyze Abstracts" should be completely separate from the search box. For example, the search box does not affect the behavior of the Analyze Abstracts button. Just make it entirely different app. As one option, you can consider having two completely different apps on a single landing page, like we did with some of the PV tools work in our own group: https://pvtools.lbl.gov . Or you could do something more conventional like a menu bar or top bar with links to various apps.

2. While I agree there should be just a single unified search, keep in mind that our app is different than a Google search in that you can't just type anything (e.g., "good battery material") and expect sensible results. There is a very strict list of approved entities that allow you to make use of the entity search (and as we discussed previously, the normalized entity search is really the advantage of this app versus something like Google Scholar that already allows you to do a direct text search). So, I really want better "hints" of what are approved entities. When you start typing, I'd like to retain an autocomplete that shows the approved entities. But, it should be a merged list of *all* possible entities, rather than separate search boxes for each entity type.

The way that I am seeing it is somewhat complicated, but:
* if you just type a word into the search box, you do a raw search on that word
* if you type a reserved syntax into the search box like ```application: "heat shield"``` it does an entity search for application=heat shield
* if you start typing ``heat shield`` into the search box, an autocomplete popup comes up that suggests you type ```application: "heat shield"``` instead. That way the user is guided towards using the reserved entity keywords.
* If the user does a search without any reserved keywords, there should be a message at the bottom of the search box that nudges them towards trying to use keywords in their search. e.g. "A raw text-only search was performed, which is not the strength of matscholar search. To search on entities or for advanced usage, try our list of keywords"
* there should also be "advanced" keywords like ```nelements: >3``` or ```anonymous_formula: ABC3```.
* In addition to *clear* and *SIMPLE* documentation regarding the list of all keywords, above the search bar there should be a random shuffle of maybe 20 different "interesting" searches we have highlighted. Just as gray text that says: "Not sure what to try? How about: ```application: thermoelectric elements:-Pb``` or something like that.

3. If you do the above, I think you can get rid of "Advanced Search" entirely for now since all the various fields can be queried using something like ```anonymous_formula: ABC3``` in the main search box. Maybe in the future we can rename it "Guided Search" or something. But we might not need it at all.

4. Regarding the output, I like the dropdown for "View Everything" vs only certain things. But, if you only view a single output, it should only query that one output. The way you described it to me, it was always doing the full query on everythign even if was only displaying one type of output. This is just for speed reasons.

5. Make sure that the fastest-to-compute output is loaded and shown first. We want the user to see *something* as fast as possible.

Let me know what you think!

**Comment by ardunn** [comment]
I do not think it would be overly complicated if that is the only search box we have. All sounds very reasonable to me. Also the "interesting" searches sound like a great way for people to get acquainted with the tool.

**Comment by ardunn** [comment]
superseded by #95
